/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        heading: ['Space Grotesk', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: '#00D1FF', // Electric Cyan
          dark: '#00B2D9',
        },
        background: '#0B0F14', // Deep System Dark
        surface: '#12181F', // Slightly lighter panel
        border: '#1E262F',
        foreground: '#F0F4F8',
        muted: '#64748B',
      },
    },
  },
  safelist: [
    'font-semibold',
    'leading-tight',
    'text-4xl',
    'text-3xl',
    'text-2xl',
    'md:text-5xl',
    'md:text-4xl',
    'md:text-3xl',
    'lg:text-6xl',
    'py-16',
    'md:py-20',
    'px-4',
    'mx-auto',
    'max-w-7xl',
    'inline-flex',
    'items-center',
    'justify-center',
    'px-6',
    'py-3',
    'text-base',
    'font-medium',
    'rounded-lg',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'bg-transparent',
    'border',
    'relative',
    'mb-12',
    'pb-4',
    'after:absolute',
    'after:bottom-0',
    'after:left-0',
    'after:h-1',
    'after:w-24',
    'after:rounded-full',
    'fixed',
    'top-0',
    'left-0',
    'h-1',
    'z-50',
    'p-6',
    'rounded-xl',
    'shadow-md',
    'hover:shadow-lg',
  ],
  plugins: [],
}